# -*- doom-docs -*-
#+title:    :tools terraform
#+subtitle: Infrastructure as code
#+created:  November 21, 2019
#+since:    21.12.0

* Description :unfold:
This module adds support for working with [[https://www.terraform.io][Terraform]] files within Emacs. This
includes syntax highlighting, intelligent code completion, and the ability to
run Terraform commands directly from Emacs.

** Maintainers
/This module has no dedicated maintainers./ [[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
- +lsp ::
  Enable LSP support for ~terraform-mode~. Requires [[module::tools lsp]] and a langserver
  (supports terraform-ls or terraform-lsp).

** Packages
- [[package:company-terraform]] if [[pkg::completion company]]
- [[package:terraform-mode]]

** Hacks
/No hacks documented for this module./

* Installation
[[id:01cffea4-3329-45e2-a892-95a384ab2338][Enable this module in your ~doom!~ block.]]

This module requires the ~terraform~ executable to be installed and in your
=$PATH=.

* Usage
** Syntax highlighting
Syntax highlighting is provided from ~terraform-mode~ and ~hcl-mode~.

** Code formatting
[[module::tools terraform]] does not provide code formatting directly, but [[module::editor format]]
works with Terraform files.

** Code navigation
Code navigation is supported through [[pkg:imenu]] from [[pkg:terraform-mode]].

** Code completion
Code completion of Terraform builtins is provided from [[pkg:company-terraform]] and
generally works well despite being generated through a [[https://github.com/rafalcieslak/emacs-company-terraform/blob/master/company-terraform-data.el][static (outdated) file]].

[[pkg:company-terraform]] also provides code completion of resources within your
project.

** Documentation
Documentation is accessible through the normal [[pkg:company]] show documentation
functionality, thanks to [[pkg:company-terraform]].

** Executing Terraform commands
[[module::tools terraform]] provides commands under [[kbd:][<localleader>]] to run the most common
Terraform operations:
| key             | description              |
|-----------------+--------------------------|
| [[kbd:][<localleader> i]] | Runs ~$ terraform init~  |
| [[kbd:][<localleader> p]] | Runs ~$ terraform plan~  |
| [[kbd:][<localleader> a]] | Runs ~$ terraform apply~ |

* TODO Configuration
#+begin_quote wip
This module has no configuration documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* Troubleshooting
/There are no known problems with this module./ [[doom-report:][Report one?]]

* Frequently asked questions
/This module has no FAQs yet./ [[doom-contrib-faq:][Ask one?]]
