# -*- doom-docs -*-
#+title:    :lang yaml
#+subtitle: JSON, but readable
#+created:  April 24, 2020
#+since:    21.12.0

* Description :unfold:
This module provides support for the [[https://yaml.org/][YAML file format]] to Doom Emacs.

** Maintainers
/This module has no dedicated maintainers./ [[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
- +lsp ::
  Enable LSP support for ~yaml-mode~. Requires [[module::tools lsp]] and a
  langserver (supports [[https://github.com/redhat-developer/yaml-language-server][yaml-language-server]]).
- +tree-sitter ::
  Leverages tree-sitter for better syntax highlighting and structural text
  editing. Requires [[module::tools tree-sitter]].

** Packages
- [[package:yaml-mode]]

** Hacks
/No hacks documented for this module./

* Installation
[[id:01cffea4-3329-45e2-a892-95a384ab2338][Enable this module in your ~doom!~ block.]]

** Formatter

Formatting is handled using the [[module::editor format]] module via [[https://prettier.io/docs/en/install.html][prettier]].

* TODO Usage
#+begin_quote wip
This module has no usage documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* TODO Configuration
#+begin_quote wip
This module has no configuration documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* TODO Troubleshooting
/There are no known problems with this module./ [[doom-report:][Report one?]]

* Frequently asked questions
/This module has no FAQs yet./ [[doom-contrib-faq:][Ask one?]]
