;;; modules/email/mu4e/compat/1.14.el -*- lexical-binding: t; -*-
;;; Commentary:
;;
;; REVIEW: Remove me if tecosaur/mu4e-compat#1 is merged/resolved.
;;
;;; Code:

(setq mu4e-compat--needlessly-breaking-renames-sofar
      '(("1.8"
         (mu4e~mark-find-headers-buffer . mu4e--mark-find-headers-buffer)
         (mu4e~update-name . mu4e--update-name)
         (mu4e~main-action-str . mu4e--main-action-str)
         (mu4e~main-toggle-mail-sending-mode . mu4e--main-toggle-mail-sending-mode)
         (mu4e~log-buffer-name . mu4e--log-buffer-name)
         (mu4e~stop . mu4e--stop)
         (mu4e~mark-get-dyn-target . mu4e--mark-get-dyn-target)
         (mu4e~mark-initialize . mu4e--mark-initialize)
         (mu4e~progress-reporter . mu4e--progress-reporter)
         (mu4e~get-mail-process-filter . mu4e--get-mail-process-filter)
         (mu4e~update-mail-and-index-real . mu4e--update-mail-and-index-real)
         (mu4e~main-view-real . mu4e--main-view-real)
         (mu4e~server-props . mu4e--server-props)
         (mu4e~mark-fringe . mu4e--mark-fringe)
         (mu4e~lists-hash . mu4e--lists-hash)
         (mu4e~mark-get-markpair . mu4e--mark-get-markpair)
         (mu4e~mark-map . mu4e--mark-map)
         (mu4e~mark-fringe-format . mu4e--mark-fringe-format)
         (mu4e~start . mu4e--start)
         (mu4e~get-folder . mu4e--get-folder)
         (mu4e~main-queue-size . mu4e--main-queue-size)
         (mu4e~main-view . mu4e--main-view)
         (mu4e~mark-get-move-target . mu4e--mark-get-move-target)
         (mu4e~mark-clear . mu4e--mark-clear)
         (mu4e~get-mail-password-regexp . mu4e--get-mail-password-regexp)
         (mu4e~mark-fringe-len . mu4e--mark-fringe-len)
         (mu4e~active-composition-buffers . mu4e--active-composition-buffers)
         (mu4e~main-view-queue . mu4e--main-view-queue)
         (mu4e~main-menu . mu4e--main-menu)
         (mu4e~read-char-choice . mu4e--read-char-choice)
         (mu4e~rfc822-phrase-type . mu4e--rfc822-phrase-type)
         (mu4e~temp-window . mu4e--temp-window)
         (mu4e~default-handler . mu4e--default-handler)
         (mu4e~update-buffer . mu4e--update-buffer)
         (mu4e-refresh-message . mu4e--refresh-message)
         (mu4e~replace-first-line-matching . mu4e--replace-first-line-matching)
         (mu4e~contains-line-matching . mu4e--contains-line-matching)
         (mu4e~check-requirements . mu4e--check-requirements)
         (mu4e~context-ask-user . mu4e--context-ask-user)
         (mu4e~update-timer . mu4e--update-timer)
         (mu4e~get-mail-ask-password . mu4e--get-mail-ask-password)
         (mu4e~mark-ask-target . mu4e--mark-ask-target)
         (mu4e-error-handler . mu4e--error-handler)
         (mu4e~context-current . mu4e--context-current)
         (mu4e~update-buffer-height . mu4e--update-buffer-height)
         (mu4e~context-autoswitch . mu4e--context-autoswitch)
         (mu4e~update-sentinel-func . mu4e--update-sentinel-func)
         (mu4e-info-handler . mu4e--info-handler)
         (mu4e~guess-maildir . mu4e--guess-maildir)
         (mu4e-context-current . mu4e--context-current)
         (mu4e~mark-check-target . mu4e--mark-check-target))
        ("1.10"
         (mu4e~view-get-urls-num . mu4e--view-get-urls-num)
         (mu4e~view-link-map . mu4e--view-link-map)
         (mu4e~view-get-property-from-event . mu4e--view-get-property-from-event)
         (mu4e~view-raw-buffer-name . mu4e--view-raw-buffer-name)
         (mu4e~view-handle-multi-urls . mu4e--view-handle-multi-urls)
         (mu4e~view-split-view-p . mu4e--view-split-view-p)
         (mu4e~view-handle-single-url . mu4e--view-handle-single-url)
         (mu4e~view-browse-url-from-binding . mu4e--view-browse-url-from-binding)
         (mu4e~view-beginning-of-url-regexp . mu4e--view-beginning-of-url-regexp)
         (mu4e~view-handle-urls . mu4e--view-handle-urls)
         (mu4e~get-maildirs-1 . mu4e--get-maildirs-1))
        ("1.12"
         (mu4e~compose-complete-handler . mu4e--compose-complete-handler)
         (mu4e~compose-setup-completion . mu4e--compose-setup-completion)
         (mu4e~compose-set-friendly-buffer-name . mu4e--compose-set-friendly-buffer-name)
         (mu4e~compose-remap-faces . mu4e--compose-remap-faces)
         (mu4e~compose-buffer-max-name-length . mu4e--compose-buffer-max-name-length)
         (mu4e-send-harden-newlines . mu4e--send-harden-newlines))
        ("1.10"
         (mu4e~icalendar-delete-citation . mu4e--icalendar-delete-citation)
         (mu4e~view-msg-mail . mu4e--view-msg-mail)
         (mu4e~view-activate-urls . mu4e--view-activate-urls)
         (mu4e~view-gather-mime-parts . mu4e--view-gather-mime-parts)
         (mu4e~view-mode-p . mu4e--view-mode-p)
         (mu4e~view-mime-part-to-temp-file . mu4e--view-mime-part-to-temp-file)
         (mu4e~icalendar-insert-diary . mu4e--icalendar-insert-diary)
         (mu4e~view-gnus-insert-header . mu4e--view-gnus-insert-header)
         (mu4e~icalendar-trash-message-hook . mu4e--icalendar-trash-message-hook)
         (mu4e~view-render-buffer . mu4e--view-render-buffer)
         (mu4e~view-kill-mime-handles . mu4e--view-kill-mime-handles)
         (mu4e~view-open-file . mu4e--view-open-file)
         (mu4e~view-gnus-insert-header-custom . mu4e--view-gnus-insert-header-custom)
         (mu4e~icalendar-has-email . mu4e--icalendar-has-email)
         (mu4e~view-nop . mu4e--view-nop)
         (mu4e~view-gnus-display-mime . mu4e--view-gnus-display-mime)
         (mu4e~icalendar-trash-message . mu4e--icalendar-trash-message)
         (mu4e~view-button-reply . mu4e--view-button-reply))
        ("1.12"
         (mu4e-icalendar-reply . mu4e--icalendar-reply))
        ("1.14"
         (mu4e-personal-addresses . mu4e--personal-addresses))))

(setq mu4e-compat--needlessly-breaking-renames-future
      '())

;;; +compat-1.14.el ends here
