# -*- doom-docs -*-
#+title:    :lang racket
#+subtitle: The DSL for DSLs
#+created:  July 29, 2018
#+since:    2.0.9

* Description :unfold:
This module adds support for the [[https://www.racket-lang.org/][Racket programming language]] to Doom Emacs.

** Maintainers
*This module needs a maintainer.* [[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
- +lsp ::
  Enable support for ~racket-mode~. Requires [[module::tools lsp]] and a langserver
  (supports [[https://github.com/jeapostrophe/racket-langserver][racket-langserver]]).
- +xp ::
  Enable the explore minor mode (~racket-xp-mode~), which "analyzes expanded
  code to explain and explore."
- +hash-lang ::
  Enable the hash-lang major mode (~racket-hash-lang-mode~), which "uses
  color-lexer, indent, and navigation supplied by a #lang." This flag can be
  used along with the ~+xp~ flag.

** Packages
- [[package:racket-mode]]

** Hacks
/No hacks documented for this module./

* Installation
[[id:01cffea4-3329-45e2-a892-95a384ab2338][Enable this module in your ~doom!~ block.]]

This module requires ~racket~. Install it from the [[https://download.racket-lang.org/][racket website]] or through
your OS package manger.

** Arch Linux
#+begin_src sh
pacman -S racket
#+end_src

Or, for fewer dependencies:
#+begin_src sh
pacman -S racket-minimal
#+end_src

** Formatter

Formatting is handled using the [[module::editor format]] module via [[https://docs.racket-lang.org/fmt/][fmt]].

* TODO Usage
#+begin_quote wip
This module has no usage documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* TODO Configuration
#+begin_quote wip
/This module's configuration documentation is incomplete./ [[doom-contrib-module:][Complete it?]]
#+end_quote

** Unicode Input
The optional ~racket-unicode~ input method lets you type unicode characters such
as λ or π. To enable unicode input for a single buffer, run
~racket-unicode-input-method-enable~. To enable unicode input by default on all
racket buffers:
#+begin_src emacs-lisp
;; in $DOOMDIR/config.el
(add-hook 'racket-mode-hook      #'racket-unicode-input-method-enable)
(add-hook 'racket-repl-mode-hook #'racket-unicode-input-method-enable)
#+end_src

Once enabled, unicode input can be toggled by pressing C-\ or running
~toggle-input-method~.

* Troubleshooting
/There are no known problems with this module./ [[doom-report:][Report one?]]

* Frequently asked questions
/This module has no FAQs yet./ [[doom-contrib-faq:][Ask one?]]
