# -*- doom-docs -*-
#+title:    :editor snippets
#+subtitle: My elves type so I don't have to
#+created:  February 11, 2017
#+since:    2.0.0

* Description :unfold:
This module adds snippet expansions to Emacs, powered by [[pkg:yasnippet]].

** Maintainers
- [[github:hlissner]]
  
[[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
/This module exposes no flags./

** Packages
- [[package:yasnippet]]
- [[package:auto-yasnippet]]
- [[package:doom-snippets]]

** TODO Hacks
#+begin_quote wip
This module's hacks haven't been documented yet. [[doom-contrib-module:][Document them?]]
#+end_quote

* TODO Usage
#+begin_quote wip
This module has no usage documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* TODO Configuration
#+begin_quote wip
/This module's configuration documentation is incomplete./ [[doom-contrib-module:][Complete it?]]
#+end_quote

** Disabling the built-in snippets
#+begin_src emacs-lisp
;; in $DOOMDIR/packages.el
(package! doom-snippets :ignore t)
;; If you want to replace it with yasnippet's default snippets
(package! yasnippet-snippets)
#+end_src

** Adding custom snippets
Custom snippets should be added under =$DOOMDIR/snippets/= directory. Refer to [[http://joaotavora.github.io/yasnippet/snippet-development.html][yasnippet-documentation]] on how to write snippets.

* Troubleshooting
/There are no known problems with this module./ [[doom-report:][Report one?]]

* Frequently asked questions
/This module has no FAQs yet./ [[doom-contrib-faq:][Ask one?]]
