# -*- doom-docs -*-
#+title:    :lang kotlin
#+subtitle: A Java(Script) that won't depress you
#+created:  March 28, 2019
#+since:    21.12.0

* Description :unfold:
This module adds [[https://kotlinlang.org/][Kotlin]] support to Doom Emacs.

** Maintainers
*This module needs a maintainer.* [[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
- +lsp ::
  Enable LSP support for ~kotlin-mode~. Requires [[module::tools lsp]] and a langserver
  (supports [[https://github.com/emacs-lsp/lsp-mode][kotlin-language-server]]).
- +tree-sitter ::
  Leverages tree-sitter for better syntax highlighting and structural text
  editing. Requires Emacs 30.1+ and [[module::tools tree-sitter]].

** Packages
- [[package:flycheck-kotlin]] if [[module::checkers syntax]]
- [[package:kotlin-mode]]
- [[package:kotlin-ts-mode]] if [[module::+tree-sitter]]

** Hacks
/No hacks documented for this module./

* Installation
[[id:01cffea4-3329-45e2-a892-95a384ab2338][Enable this module in your ~doom!~ block.]]

Install kotlin through your distribution's package manager, eg:

#+begin_src shell
sudo apt install kotlin # Ubuntu
sudo pacman -S kotlin   # Arch Linux
brew install kotlin     # MacOS
#+end_src

or by getting the [[https://github.com/JetBrains/kotlin/releases/latest][latest]] release and adding to your =$PATH= manually.

** Formatter

Formatting is handled using the [[module::editor format]] module via [[https://pinterest.github.io/ktlint/install/cli/][ktlint]].

* TODO Usage
#+begin_quote wip
This module has no usage documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* TODO Configuration
#+begin_quote wip
This module has no configuration documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* Troubleshooting
/There are no known problems with this module./ [[doom-report:][Report one?]]

* Frequently asked questions
/This module has no FAQs yet./ [[doom-contrib-faq:][Ask one?]]
