# -*- doom-docs -*-
:PROPERTIES:
:ID:       68a51608-e252-421a-bb79-bb1f038fbf5b
:END:
#+title:     :emacs tramp
#+subtitle:  Remote files at your arthritic fingertips
#+created:   September 14, 2025
#+since:     25.10.0

* Description :unfold:
This module provides sensible and performant defaults for TRAMP, a built-in
Emacs package that provides remote file editing over various protocols like SSH,
SCP, FTP, and more.

#+begin_quote warning
The performance enhancements in this module have the greatest effects in later
versions of Emacs (at least 30.1 is recommended).
#+end_quote

** Maintainers
- [[github:hlissner]]

[[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
/This module has no flags./

** Packages
/This module doesn't install any packages./

** Hacks
- Turns on tramp-direct-async-process globally (for improved performance), but
  disables it for lsp-mode/eglot connections to LSP servers.
- In remote buffers, several functions are memoized to reduce I/O over TRAMP and
  improve performance. Currently, these functions are ~magit-toplevel~,
  ~project-current~, and ~vc-git-root~.

* Installation
[[id:01cffea4-3329-45e2-a892-95a384ab2338][Enable this module in your ~doom!~ block.]]

/This module has no external requirements./

* Usage
#+begin_quote wip
This module has no usage documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* TODO Configuration
#+begin_quote wip
This module has no configuration documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* Troubleshooting
[[doom-report:][Report an issue?]]

** Known compatibility issues
- gdb-mi (via ~M-x gdb~) ::
  Doesn't work with direct-async enabled. To get around this, add ~set debuginfod
  enabled~ to =~/.gdbinit= (reported in [[github:doomemacs/core/issues/8510][doomemacs/core#8510]]).

* Frequently asked questions
/This module has no FAQs yet./ [[doom-contrib-faq:][Ask one?]]
