# -*- doom-docs -*-
#+title:    :lang json
#+subtitle: At least it ain't XML
#+created:  April 23, 2020
#+since:    21.12.0

* Description :unfold:
This module adds [[https://www.json.org/json-en.html][JSON]] support to Doom Emacs.

** Maintainers
/This module has no dedicated maintainers./ [[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
- +lsp ::
  Enable LSP support for [[major:json-mode]]. Requires [[module::tools lsp]] and a langserver
  (supports [[https://github.com/vscode-langservers/vscode-json-languageserver][vscode-json-languageserver]]).
- +tree-sitter ::
  Leverages tree-sitter for better syntax highlighting and structural text
  editing. Requires Emacs 29.1+ and [[module::tools tree-sitter]].

** Packages
- [[package:counsel-jq]] if [[module::completion ivy]]
- [[package:json-mode]]
- [[package:json-snatcher]]

** Hacks
/No hacks documented for this module./

* Installation
[[id:01cffea4-3329-45e2-a892-95a384ab2338][Enable this module in your ~doom!~ block.]]

** Formatter

Formatting is handled using the [[module::editor format]] module via [[https://prettier.io/docs/en/install.html][prettier]].

* TODO Usage
#+begin_quote wip
This module has no usage documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* TODO Configuration
#+begin_quote wip
This module has no configuration documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* Troubleshooting
/There are no known problems with this module./ [[doom-report:][Report one?]]

* Frequently asked questions
/This module has no FAQs yet./ [[doom-contrib-faq:][Ask one?]]
