# -*- doom-docs -*-
#+title:    :lang purescript
#+subtitle: Javascript, but functional
#+created:  May 21, 2017
#+since:    2.0.3

* Description :unfold:
This module adds [[https://www.purescript.org/][Purescript]] support to Doom Emacs.

** Maintainers
*This module needs a maintainer.* [[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
- +lsp ::
  Enable LSP support for ~purescript-mode~. Requires [[module::tools lsp]] and a langserver
  (supports [[https://github.com/nwolverson/purescript-language-server][purescript-language-server]]).

** Packages
- [[package:psci]]
- [[package:psc-ide]]
- [[package:purescript-mode]]

** Hacks
/No hacks documented for this module./

* Installation
[[id:01cffea4-3329-45e2-a892-95a384ab2338][Enable this module in your ~doom!~ block.]]

The main tools for PureScript are installed via npm.

** Compiler
#+begin_src shell
npm install -g purescript spago
#+end_src

** Formatter
#+begin_src sh
npm install -g purs-tidy
#+end_src

* TODO Usage
#+begin_quote wip
This module has no usage documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* TODO Configuration
#+begin_quote wip
This module has no configuration documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* Troubleshooting
/There are no known problems with this module./ [[doom-report:][Report one?]]

* Frequently asked questions
/This module has no FAQs yet./ [[doom-contrib-faq:][Ask one?]]
