# -*- doom-docs -*-
#+title:    :lang julia
#+subtitle: A better, faster MATLAB
#+created:  April 08, 2020
#+since:    1.3

* Description :unfold:
This module adds support for [[https://julialang.org/][the Julia language]] to Doom Emacs.

- Syntax highlighting and latex symbols from [[pkg:julia-mode]]
- REPL integration from [[pkg:julia-repl]]
- Code completion and syntax checking, requires [[module::tools lsp]] and [[module:+lsp]]

** Maintainers
/This module has no dedicated maintainers./ [[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
- +lsp ::
  Enable LSP support for ~julia-mode~. Requires [[module::tools lsp]] and a
  langserver (supports LanguageServer.jl).
- +tree-sitter ::
  Leverages tree-sitter for better syntax highlighting and structural text
  editing. Requires [[module::tools tree-sitter]].
- +snail ::
  Use Snail, a development environment and REPL interaction package for Julia in
  the spirit of Common Lisp’s SLIME and Clojure’s CIDER. It enables convenient
  and dynamic REPL-driven development.

** Packages
- [[package:julia-mode]]
- [[package:julia-repl]]
- if [[module:+lsp]]
  - if [[module::tools lsp]]
    - [[package:lsp-julia]]
    - [[package:lsp]]
  - if [[module::tools lsp +eglot]]
    - [[package:eglot-jl]]
    - [[package:eglot]]
- if [[module:+snail]]
  - [[package:julia-snail]]

** Hacks
/No hacks documented for this module./

* Installation
[[id:01cffea4-3329-45e2-a892-95a384ab2338][Enable this module in your ~doom!~ block.]]

This module requires [[https://julialang.org/][Julia]] and an language server if [[module:+lsp]] is enabled.

** Language Server
[[module:+lsp]] requires ~LanguageServer.jl~ and ~SymbolServer.jl~. The [[pkg:lsp-julia]] and
[[pkg:eglot-jl]] packages both come bundled with their own versions of these servers,
which is used by default. If you're happy with that, no further configuration is
necessary.

However, to use your own installation you will need to install then configure
them. To install them, execute these commands in a Julia REPL:
#+begin_src julia
using Pkg
Pkg.add("LanguageServer")
Pkg.add("SymbolServer")
#+end_src

Then configure [[pkg:lsp-julia]] or [[pkg:eglot-jl]] depending on whether you have enabled [[module::tools
lsp]] or [[module::tools lsp +eglot]], respectively:

*** =lsp-julia=
To instruct [[pkg:lsp-julia]] not to use the built-in package:
#+begin_src emacs-lisp
;; in $DOOMDIR/config.el
(setq lsp-julia-package-dir nil)
#+end_src

To find your installation of ~LanguageServer.jl~, [[pkg:lsp-julia]] needs to know the
environment in which it is installed. This is set to v1.6 by default as it is
the current LTS:
#+begin_src emacs-lisp
;; in $DOOMDIR/config.el
(with-eval-after-load 'lsp-julia
  (setq lsp-julia-default-environment "~/.julia/environments/v1.6"))
#+end_src

*** =eglot-jl=
To find your installation of ~LanguageServer.jl~, [[pkg:eglot-jl]] must know the
environment in which it is installed. This is set to v1.6 by default as it is
the current LTS:
#+begin_src emacs-lisp
;; in $DOOMDIR/config.el
(setq eglot-jl-language-server-project "~/.julia/environments/v1.6")
#+end_src

But to let [[pkg:eglot-jl]] use the environment bundled with it, set it to
~eglot-jl-base~ instead:
#+begin_src emacs-lisp
;; in $DOOMDIR/config.el
(with-eval-after-load 'eglot-jl
  (setq eglot-jl-language-server-project eglot-jl-base))
#+end_src

* TODO Usage
#+begin_quote wip
/This module's usage documentation is incomplete./ [[doom-contrib-module:][Complete it?]]
#+end_quote

** Language Server
[[module:+lsp]] adds code completion, syntax checking, formatting and other [[pkg:lsp-mode]] or
[[pkg:eglot]] features. It requires ~LanguageServer.jl~, the installation of which is
described above.

** Snail

| Keybind                     | Command                           |
|-----------------------------+-----------------------------------|
| [[kbd:][<localleader> ']]   | ~julia-snail~                     |
| [[kbd:][<localleader> a]]   | ~julia-snail-package-activate~    |
| [[kbd:][<localleader> r]]   | ~julia-snail-update-module-cache~ |
| [[kbd:][<localleader> d]]   | ~julia-snail-doc-lookup~          |
| [[kbd:][<localleader> e b]] | ~julia-snail-send-buffer-file~    |
| [[kbd:][<localleader> e l]] | ~julia-snail-send-line~           |
| [[kbd:][<localleader> e r]] | ~julia-snail-send-region~         |
| [[kbd:][<localleader> e e]] | ~julia-snail-send-dwim~           |

* TODO Configuration
#+begin_quote wip
/This module's configuration documentation is incomplete./ [[doom-contrib-module:][Complete it?]]
#+end_quote

** Change the default environment for the Julia language server
[[pkg:lsp-julia]] requires a variable be set for the Julia environment. This is set to
v1.6 by default as it is the current LTS:
#+begin_src emacs-lisp
;; in $DOOMDIR/config.el
(with-eval-after-load 'lsp-julia
  (setq lsp-julia-default-environment "~/.julia/environments/v1.6"))
#+end_src

* Troubleshooting
/There are no known problems with this module./ [[doom-report:][Report one?]]

* Frequently asked questions
/This module has no FAQs yet./ [[doom-contrib-faq:][Ask one?]]
