# -*- doom-docs -*-
#+title:    :lang erlang
#+subtitle: an elegant language for a more civilized age
#+created:  April 07, 2018
#+since:    21.12.0

* Description :unfold:
This module provides support [[https://www.erlang.org/][Erlang programming language]]. Support for the
[[https://github.com/erlang/sourcer][sourcer]] language server is optional.

Includes:
- Code completion ([[module:+lsp]], [[module::completion company]], & [[module::completion ivy]])
- Syntax checking ([[module::checkers syntax]])

** Maintainers
/This module has no dedicated maintainers./ [[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
- +lsp ::
  Enable LSP support for ~erlang-mode~. Requires [[module::tools lsp]] and a langserver
  (supports [[https://github.com/erlang/sourcer][sourcer]]).
- +tree-sitter ::
  Leverages tree-sitter for better syntax highlighting and structural text
  editing. Requires [[module::tools tree-sitter]].

** Packages
- [[package:flycheck-rebar3]]
- [[package:ivy-erlang-complete]]

** Hacks
/No hacks documented for this module./

* Installation
[[id:01cffea4-3329-45e2-a892-95a384ab2338][Enable this module in your ~doom!~ block.]]

This module requires Erlang be installed (which includes ~erlang-mode~). Check
your distribution's package manager or a version management tool such as [[https://github.com/kerl/kerl][kerl]].

- [[https://github.com/erlang/sourcer][sourcer]] when [[module::tools lsp]] & [[module:+lsp]]
- [[https://github.com/erlang/rebar3][rebar3]] with [[https://github.com/WhatsApp/erlfmt][erlfmt]] when [[module::editor format]]

* TODO Usage
#+begin_quote wip
This module has no usage documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

** formatter
By enabling [[module::editor format]], [[pkg:apheleia]] will be
used to format the current buffer.

Enable [[module::editor format +onsave]] to format the buffer on save.

* TODO Configuration
#+begin_quote wip
This module has no configuration documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* Troubleshooting
/There are no known problems with this module./ [[doom-report:][Report one?]]

* Frequently asked questions
/This module has no FAQs yet./ [[doom-contrib-faq:][Ask one?]]
