# -*- doom-docs -*-
#+title:    :lang fsharp
#+subtitle: ML stands for Microsoft's Language
#+created:  May 23, 2019
#+since:    21.12.0

* Description :unfold:
This module adds [[https://fsharp.org/][F#]] support to Doom Emacs.

*Includes:*
- Code completion
- eldoc support
- Syntax checking

** Maintainers
/This module has no dedicated maintainers./ [[doom-contrib-maintainer:][Become a maintainer?]]

** Module flags
- +lsp ::
  Enable LSP support for ~fsharp-mode~. Requires [[module::tools lsp]] and a langserver
  (supports [[https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-fsharp.el][lsp-fsharp]].).
- +tree-sitter ::
  Leverages tree-sitter for better syntax highlighting and structural text
  editing. Requires Emacs 29.1+ and [[module::tools tree-sitter]].

** Packages
- [[package:fsharp-mode]]
- [[package:fsharp-ts-mode]] if [[module:+tree-sitter]]
- [[package:lsp-fsharp]] if [[pkg:+lsp]]

** Hacks
/No hacks documented for this module./

* Installation
[[id:01cffea4-3329-45e2-a892-95a384ab2338][Enable this module in your ~doom!~ block.]]

To get code completion/syntax checking when not using lsp, you will need to
install [[https://www.mono-project.com/][mono]].

** Mono
*** OSX
*Do NOT install mono via brew.* See this [[https://github.com/fsharp/FsAutoComplete/issues/331][issue]].

*** Arch Linux
#+begin_src sh
pacman -S mono
#+end_src

** LSP
The language server is automatically installed by [[https://github.com/emacs-lsp/lsp-mode/blob/master/clients/lsp-fsharp.el][lsp-fsharp]].

** Fantomas
Fantomas is used for formatting via [[module::editor format]] and can be installed as a [[https://dotnet.microsoft.com/en-us/download][dotnet]] tool. 

#+begin_src shell
dotnet tool install -g fantomas-tool
#+end_src

* TODO Usage
#+begin_quote wip
This module has no usage documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* TODO Configuration
#+begin_quote wip
This module has no configuration documentation yet. [[doom-contrib-module:][Write some?]]
#+end_quote

* Troubleshooting
/There are no known problems with this module./ [[doom-report:][Report one?]]

* Frequently asked questions
/This module has no FAQs yet./ [[doom-contrib-faq:][Ask one?]]
